CREATE DATABASE IF NOT EXISTS pagamento;
CREATE DATABASE IF NOT EXISTS dashboard;
CREATE DATABASE IF NOT EXISTS notas_fiscais;
CREATE DATABASE IF NOT EXISTS notificacoes;
CREATE DATABASE IF NOT EXISTS usuario;
