services:
  autenticacao:
    build:
      context: .
      args:
        APP_NAME: autenticacao
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    depends_on:
      - redis

  dashboard:
    build:
      context: .
      args:
        APP_NAME: dashboard
    ports:
      - "3001:3000"
    environment:
      - PORT=3000
    depends_on:
      - redis

  notas_fiscais:
    build:
      context: .
      args:
        APP_NAME: notas-fiscais
    ports:
      - "3002:3000"
    environment:
      - PORT=3000
    depends_on:
      - redis

  notificacoes:
    build:
      context: .
      args:
        APP_NAME: notificacoes
    ports:
      - "3003:3000"
    environment:
      - PORT=3000
    depends_on:
      - redis

  usuario:
    build:
      context: .
      args:
        APP_NAME: usuario
    ports:
      - "3004:3000"
    depends_on:
      - redis

  redis:
    image: redis:7
    ports:
      - "6379:6379"
